language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

script:
  - pytest --cov=banyan tests/
  - flake8 --exit-zero
  - python setup.py sdist bdist_wheel

after_success:
  - codecov
  - twine upload dist/*
